version: '3.4'

services:
  kysliotek:
    image: ${DOCKER_REGISTRY-}kysliotek
    build:
      context: .
      dockerfile: KYSliotek/Dockerfile

    
  ravendbservice:
    container_name: 4_Semester_Project_ravendb
    image: ravendb/ravendb   
    ports:
      - 8080:8080
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_ARGS="--Setup.Mode=None"

  eventstore:
    container_name: 4_Semester_Project-eventstore
    image: eventstore/eventstore:20.6.0-buster-slim
    command: --enable-external-tcp --ext-ip=0.0.0.0 --int-ip=0.0.0.0 --disable-external-tcp-tls
    ports:
        - 3113:3113
        - 4113:4113
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_HTTP_PORT=3113
      - EVENTSTORE_EXT_TCP_PORT=4113
      - EVENTSTORE_DEV= true
    restart: always