version: '3.4'

services: 
  ravendbservice:
    container_name: 4_Semester_Project_ravendb
    image: ravendb/ravendb   
    ports:
      - 8080:8080
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_ARGS="--Setup.Mode=None"

  eventstore:
    container_name: 4_Semester_Project-eventstore
    image: eventstore/eventstore:20.6.0-buster-slim
    command: --enable-external-tcp --ext-ip=0.0.0.0 --int-ip=0.0.0.0 --disable-external-tcp-tls
    ports:
        - 2113:2113
        - 1113:1113
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INT_HTTP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INTTCP_PORT=1112
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_DEV= true
    restart: always
   

  
